'use strict';

pokerApp.factory('deckService', ['constants', function (consts) {
    return  {
        deck: [
            {rank: consts.Ranks.ACE, color: consts.Colors.CLUBS, img: 'img/1.png'},
            {rank: consts.Ranks.ACE, color: consts.Colors.DIAMONDS, img: 'img/4.png'},
            {rank: consts.Ranks.ACE, color: consts.Colors.HEARTS, img: 'img/3.png'},
            {rank: consts.Ranks.ACE, color: consts.Colors.SPADES, img: 'img/2.png'},
            {rank: consts.Ranks.TWO, color: consts.Colors.CLUBS, img: 'img/49.png'},
            {rank: consts.Ranks.TWO, color: consts.Colors.DIAMONDS, img: 'img/52.png'},
            {rank: consts.Ranks.TWO, color: consts.Colors.HEARTS, img: 'img/51.png'},
            {rank: consts.Ranks.TWO, color: consts.Colors.SPADES, img: 'img/50.png'},
            {rank: consts.Ranks.THREE, color: consts.Colors.CLUBS, img: 'img/45.png'},
            {rank: consts.Ranks.THREE, color: consts.Colors.DIAMONDS, img: 'img/48.png'},
            {rank: consts.Ranks.THREE, color: consts.Colors.HEARTS, img: 'img/47.png'},
            {rank: consts.Ranks.THREE, color: consts.Colors.SPADES, img: 'img/46.png'},
            {rank: consts.Ranks.FOUR, color: consts.Colors.CLUBS, img: 'img/41.png'},
            {rank: consts.Ranks.FOUR, color: consts.Colors.DIAMONDS, img: 'img/44.png'},
            {rank: consts.Ranks.FOUR, color: consts.Colors.HEARTS, img: 'img/43.png'},
            {rank: consts.Ranks.FOUR, color: consts.Colors.SPADES, img: 'img/42.png'},
            {rank: consts.Ranks.FIVE, color: consts.Colors.CLUBS, img: 'img/37.png'},
            {rank: consts.Ranks.FIVE, color: consts.Colors.DIAMONDS, img: 'img/40.png'},
            {rank: consts.Ranks.FIVE, color: consts.Colors.HEARTS, img: 'img/39.png'},
            {rank: consts.Ranks.FIVE, color: consts.Colors.SPADES, img: 'img/38.png'},
            {rank: consts.Ranks.SIX, color: consts.Colors.CLUBS, img: 'img/33.png'},
            {rank: consts.Ranks.SIX, color: consts.Colors.DIAMONDS, img: 'img/36.png'},
            {rank: consts.Ranks.SIX, color: consts.Colors.HEARTS, img: 'img/35.png'},
            {rank: consts.Ranks.SIX, color: consts.Colors.SPADES, img: 'img/34.png'},
            {rank: consts.Ranks.SEVEN, color: consts.Colors.CLUBS, img: 'img/29.png'},
            {rank: consts.Ranks.SEVEN, color: consts.Colors.DIAMONDS, img: 'img/32.png'},
            {rank: consts.Ranks.SEVEN, color: consts.Colors.HEARTS, img: 'img/31.png'},
            {rank: consts.Ranks.SEVEN, color: consts.Colors.SPADES, img: 'img/30.png'},
            {rank: consts.Ranks.EIGHT, color: consts.Colors.CLUBS, img: 'img/25.png'},
            {rank: consts.Ranks.EIGHT, color: consts.Colors.DIAMONDS, img: 'img/28.png'},
            {rank: consts.Ranks.EIGHT, color: consts.Colors.HEARTS, img: 'img/27.png'},
            {rank: consts.Ranks.EIGHT, color: consts.Colors.SPADES, img: 'img/26.png'},
            {rank: consts.Ranks.NINE, color: consts.Colors.CLUBS, img: 'img/21.png'},
            {rank: consts.Ranks.NINE, color: consts.Colors.DIAMONDS, img: 'img/24.png'},
            {rank: consts.Ranks.NINE, color: consts.Colors.HEARTS, img: 'img/23.png'},
            {rank: consts.Ranks.NINE, color: consts.Colors.SPADES, img: 'img/22.png'},
            {rank: consts.Ranks.TEN, color: consts.Colors.CLUBS, img: 'img/17.png'},
            {rank: consts.Ranks.TEN, color: consts.Colors.DIAMONDS, img: 'img/20.png'},
            {rank: consts.Ranks.TEN, color: consts.Colors.HEARTS, img: 'img/19.png'},
            {rank: consts.Ranks.TEN, color: consts.Colors.SPADES, img: 'img/18.png'},
            {rank: consts.Ranks.JACK, color: consts.Colors.CLUBS, img: 'img/13.png'},
            {rank: consts.Ranks.JACK, color: consts.Colors.DIAMONDS, img: 'img/16.png'},
            {rank: consts.Ranks.JACK, color: consts.Colors.HEARTS, img: 'img/15.png'},
            {rank: consts.Ranks.JACK, color: consts.Colors.SPADES, img: 'img/14.png'},
            {rank: consts.Ranks.QUEEN, color: consts.Colors.CLUBS, img: 'img/9.png'},
            {rank: consts.Ranks.QUEEN, color: consts.Colors.DIAMONDS, img: 'img/12.png'},
            {rank: consts.Ranks.QUEEN, color: consts.Colors.HEARTS, img: 'img/11.png'},
            {rank: consts.Ranks.QUEEN, color: consts.Colors.SPADES, img: 'img/10.png'},
            {rank: consts.Ranks.KING, color: consts.Colors.CLUBS, img: 'img/5.png'},
            {rank: consts.Ranks.KING, color: consts.Colors.DIAMONDS, img: 'img/8.png'},
            {rank: consts.Ranks.KING, color: consts.Colors.HEARTS, img: 'img/7.png'},
            {rank: consts.Ranks.KING, color: consts.Colors.SPADES, img: 'img/6.png'}
        ]
    };
}]);