'use strict';

pokerApp.factory('deckService', ['constants', function (consts) {
    return  {
        deck: [
            {rank: consts.Ranks.ACE, color: consts.Colors.CLUBS},
            {rank: consts.Ranks.ACE, color: consts.Colors.DIAMONDS},
            {rank: consts.Ranks.ACE, color: consts.Colors.HEARTS},
            {rank: consts.Ranks.ACE, color: consts.Colors.SPADES},
            {rank: consts.Ranks.TWO, color: consts.Colors.CLUBS},
            {rank: consts.Ranks.TWO, color: consts.Colors.DIAMONDS},
            {rank: consts.Ranks.TWO, color: consts.Colors.HEARTS},
            {rank: consts.Ranks.TWO, color: consts.Colors.SPADES},
            {rank: consts.Ranks.THREE, color: consts.Colors.CLUBS},
            {rank: consts.Ranks.THREE, color: consts.Colors.DIAMONDS},
            {rank: consts.Ranks.THREE, color: consts.Colors.HEARTS},
            {rank: consts.Ranks.THREE, color: consts.Colors.SPADES},
            {rank: consts.Ranks.FOUR, color: consts.Colors.CLUBS},
            {rank: consts.Ranks.FOUR, color: consts.Colors.DIAMONDS},
            {rank: consts.Ranks.FOUR, color: consts.Colors.HEARTS},
            {rank: consts.Ranks.FOUR, color: consts.Colors.SPADES},
            {rank: consts.Ranks.FIVE, color: consts.Colors.CLUBS},
            {rank: consts.Ranks.FIVE, color: consts.Colors.DIAMONDS},
            {rank: consts.Ranks.FIVE, color: consts.Colors.HEARTS},
            {rank: consts.Ranks.FIVE, color: consts.Colors.SPADES},
            {rank: consts.Ranks.SIX, color: consts.Colors.CLUBS},
            {rank: consts.Ranks.SIX, color: consts.Colors.DIAMONDS},
            {rank: consts.Ranks.SIX, color: consts.Colors.HEARTS},
            {rank: consts.Ranks.SIX, color: consts.Colors.SPADES},
            {rank: consts.Ranks.SEVEN, color: consts.Colors.CLUBS},
            {rank: consts.Ranks.SEVEN, color: consts.Colors.DIAMONDS},
            {rank: consts.Ranks.SEVEN, color: consts.Colors.HEARTS},
            {rank: consts.Ranks.SEVEN, color: consts.Colors.SPADES},
            {rank: consts.Ranks.EIGHT, color: consts.Colors.CLUBS},
            {rank: consts.Ranks.EIGHT, color: consts.Colors.DIAMONDS},
            {rank: consts.Ranks.EIGHT, color: consts.Colors.HEARTS},
            {rank: consts.Ranks.EIGHT, color: consts.Colors.SPADES},
            {rank: consts.Ranks.NINE, color: consts.Colors.CLUBS},
            {rank: consts.Ranks.NINE, color: consts.Colors.DIAMONDS},
            {rank: consts.Ranks.NINE, color: consts.Colors.HEARTS},
            {rank: consts.Ranks.NINE, color: consts.Colors.SPADES},
            {rank: consts.Ranks.TEN, color: consts.Colors.CLUBS},
            {rank: consts.Ranks.TEN, color: consts.Colors.DIAMONDS},
            {rank: consts.Ranks.TEN, color: consts.Colors.HEARTS},
            {rank: consts.Ranks.TEN, color: consts.Colors.SPADES},
            {rank: consts.Ranks.JACK, color: consts.Colors.CLUBS},
            {rank: consts.Ranks.JACK, color: consts.Colors.DIAMONDS},
            {rank: consts.Ranks.JACK, color: consts.Colors.HEARTS},
            {rank: consts.Ranks.JACK, color: consts.Colors.SPADES},
            {rank: consts.Ranks.QUEEN, color: consts.Colors.CLUBS},
            {rank: consts.Ranks.QUEEN, color: consts.Colors.DIAMONDS},
            {rank: consts.Ranks.QUEEN, color: consts.Colors.HEARTS},
            {rank: consts.Ranks.QUEEN, color: consts.Colors.SPADES},
            {rank: consts.Ranks.KING, color: consts.Colors.CLUBS},
            {rank: consts.Ranks.KING, color: consts.Colors.DIAMONDS},
            {rank: consts.Ranks.KING, color: consts.Colors.HEARTS},
            {rank: consts.Ranks.KING, color: consts.Colors.SPADES}
        ]
    };
}]);